
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[Rates])') AND OBJECTPROPERTY(ID,N'ISUSERTABLE')=1)
DROP TABLE [dbo].[Rates]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Rates](
	[Rate_ID] [int] IDENTITY(1,1) NOT NULL,
	[CFT_ID] [int] NULL,
	[Distance_ID] [int] NULL,
	[Freight_Rate] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[Rate_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Rates]  WITH CHECK ADD FOREIGN KEY([CFT_ID])
REFERENCES [dbo].[CFT_Range] ([CFT_ID])
GO

ALTER TABLE [dbo].[Rates]  WITH CHECK ADD FOREIGN KEY([Distance_ID])
REFERENCES [dbo].[Distance_Range] ([Distance_ID])
GO


